// ============================================
// Tirumala Mutual Fund Services
// Business Constants & Site Configuration
// ============================================

export const SITE_CONFIG = {
  name: 'Tirumala Mutual Fund Services',
  shortName: 'TMFS',
  tagline: 'Growing Wealth with Trust, Discipline & Experience.',
  headline: 'Building Wealth. Creating Financial Freedom.',
  subheadline: 'Helping individuals and families achieve their financial goals through disciplined investing and trusted financial advice.',
  domain: 'tirumalamutualfunds.in',
  url: 'https://tirumalamutualfunds.in',
  logo: '/images/logo.jpeg',
  favicon: '/favicon.ico',
} as const;

export const BUSINESS_INFO = {
  arn: 'ARN-144270',
  registration: 'AMFI Registered Mutual Fund Distributor',
  sebiStatus: 'SEBI Registered Financial Advisor / Distributor',
  experience: '15+',
  clients: '300+',
  aum: '₹10+ Crore',
  managingDirector: 'Mr. Tirumala Talabaktula',
  directorImage: '/images/director.jpeg',
} as const;

export const CONTACT_INFO = {
  mobile: '8763732389',
  mobileFormatted: '+91 87637 32389',
  landline: '06854-357410',
  email: 'tiru.jeypore@gmail.com',
  whatsapp: '918763732389',
  whatsappLink: 'https://wa.me/918763732389',
  address: {
    line1: 'MR Towers, Flat No. 105',
    line2: 'Indira Chowk',
    city: 'Jeypore',
    state: 'Odisha',
    pin: '764001',
    coordinates: '18°51\'10.4"N 82°34\'40.6"E',
    full: 'MR Towers, Flat No. 105, Indira Chowk, Jeypore, Odisha – 764001 (18°51\'10.4"N 82°34\'40.6"E)',
  },
  officeHours: {
    days: 'Monday – Saturday',
    time: '9:30 AM – 6:00 PM',
    closed: 'Sunday Closed',
  },
} as const;

export const SOCIAL_LINKS = {
  facebook: 'https://www.facebook.com/tirumala.mutual.funds',
  instagram: 'https://www.instagram.com/tirumala.mutual.funds',
  twitter: '',
  linkedin: '',
  youtube: '',
} as const;

export const STATS = [
  { value: 15, suffix: '+', label: 'Years Experience', icon: 'Trophy' },
  { value: 300, suffix: '+', label: 'Happy Clients', icon: 'Users' },
  { value: 10, prefix: '₹', suffix: '+ Cr', label: 'Assets Under Management', icon: 'TrendingUp' },
  { value: 100, suffix: '%', label: 'Transparent Advice', icon: 'Shield' },
] as const;

export const NAVIGATION = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about' },
  {
    label: 'Services',
    href: '/services',
    children: [
      { label: 'SIP', href: '/services/sip' },
      { label: 'Mutual Funds', href: '/services/mutual-funds' },
      { label: 'ELSS – Tax Saving', href: '/services/elss' },
      { label: 'SWP', href: '/services/swp' },
      { label: 'STP', href: '/services/stp' },
      { label: 'PMS', href: '/services/pms' },
      { label: 'AIF', href: '/services/aif' },
      { label: 'SIF', href: '/services/sif' },
      { label: 'NPS', href: '/services/nps' },
      { label: 'Retirement Planning', href: '/services/retirement-planning' },
      { label: 'Children\'s Education', href: '/services/education-planning' },
      { label: 'Goal Based Planning', href: '/services/goal-planning' },
      { label: 'Wealth Creation', href: '/services/wealth-creation' },
      { label: 'Portfolio Review', href: '/services/portfolio-review' },
      { label: 'Financial Planning', href: '/services/financial-planning' },
      { label: 'Term Insurance', href: '/services/term-insurance' },
      { label: 'Health Insurance', href: '/services/health-insurance' },
      { label: 'Loan Services', href: '/services/loan-services' },
      { label: 'Emergency Fund', href: '/services/emergency-fund' },
      { label: 'Corporate Investments', href: '/services/corporate-investments' },
    ],
  },
  {
    label: 'Calculators',
    href: '/calculators',
    children: [
      { label: 'SIP Calculator', href: '/calculators/sip' },
      { label: 'Lumpsum Calculator', href: '/calculators/lumpsum' },
      { label: 'Retirement Planner', href: '/calculators/retirement' },
      { label: 'Education Planner', href: '/calculators/education' },
      { label: 'Goal Planner', href: '/calculators/goal' },
    ],
  },
  { label: 'News & NFOs', href: '/news' },
  { label: 'Gallery', href: '/gallery' },
  { label: 'Blog', href: '/blog' },
  { label: 'FAQs', href: '/faq' },
  { label: 'Contact', href: '/contact' },
] as const;

export const SERVICES_DATA = [
  {
    slug: 'sip',
    title: 'Systematic Investment Plan (SIP)',
    shortDescription: 'Build wealth gradually with disciplined monthly investments starting from just ₹500.',
    icon: 'Repeat',
    riskLevel: 'Varies by Fund',
    suitableFor: 'Salaried individuals, beginners, long-term investors',
    benefits: ['Rupee cost averaging', 'Power of compounding', 'Disciplined investing', 'Flexible amounts'],
  },
  {
    slug: 'mutual-funds',
    title: 'Mutual Funds',
    shortDescription: 'Professionally managed diversified portfolios tailored to your financial goals and risk appetite.',
    icon: 'PieChart',
    riskLevel: 'Low to High',
    suitableFor: 'All investors',
    benefits: ['Professional management', 'Diversification', 'Liquidity', 'Transparency'],
  },
  {
    slug: 'elss',
    title: 'ELSS – Tax Saving',
    shortDescription: 'Save tax up to ₹46,800 under Section 80C while creating wealth with equity-linked savings.',
    icon: 'Receipt',
    riskLevel: 'Moderate to High',
    suitableFor: 'Tax-saving investors, salaried professionals',
    benefits: ['Tax deduction up to ₹1.5L', 'Shortest lock-in (3 years)', 'Equity growth potential', 'Dual benefit'],
  },
  {
    slug: 'swp',
    title: 'Systematic Withdrawal Plan (SWP)',
    shortDescription: 'Generate regular income from your investments with systematic periodic withdrawals.',
    icon: 'ArrowDownToLine',
    riskLevel: 'Low to Moderate',
    suitableFor: 'Retirees, regular income seekers',
    benefits: ['Regular income', 'Tax efficient', 'Capital preservation', 'Flexible withdrawals'],
  },
  {
    slug: 'stp',
    title: 'Systematic Transfer Plan (STP)',
    shortDescription: 'Strategically transfer funds between schemes to optimize returns and manage risk.',
    icon: 'ArrowRightLeft',
    riskLevel: 'Moderate',
    suitableFor: 'Investors with lumpsum wanting gradual equity exposure',
    benefits: ['Rupee cost averaging', 'Risk management', 'Optimal allocation', 'Automated transfers'],
  },
  {
    slug: 'pms',
    title: 'Portfolio Management Service (PMS)',
    shortDescription: 'Customized portfolio management for HNIs with minimum ₹50 Lakh investment.',
    icon: 'Briefcase',
    riskLevel: 'High',
    suitableFor: 'High Net Worth Individuals (HNIs)',
    benefits: ['Personalized portfolio', 'Direct equity exposure', 'Professional management', 'Detailed reporting'],
  },
  {
    slug: 'aif',
    title: 'Alternative Investment Fund (AIF)',
    shortDescription: 'Access exclusive alternative investment opportunities with sophisticated strategies.',
    icon: 'Gem',
    riskLevel: 'High',
    suitableFor: 'Ultra HNIs, institutional investors',
    benefits: ['Exclusive opportunities', 'Diversification beyond traditional assets', 'Professional management', 'Higher return potential'],
  },
  {
    slug: 'sif',
    title: 'Specialized Investment Fund (SIF)',
    shortDescription: 'SEBI\'s new asset class bridging mutual funds and PMS for informed investors.',
    icon: 'Target',
    riskLevel: 'Moderate to High',
    suitableFor: 'Informed investors seeking advanced strategies',
    benefits: ['Lower entry than PMS', 'Advanced strategies', 'Regulated framework', 'Professional management'],
  },
  {
    slug: 'nps',
    title: 'National Pension System (NPS)',
    shortDescription: 'Government-backed retirement savings with additional tax benefits under Section 80CCD.',
    icon: 'Landmark',
    riskLevel: 'Low to Moderate',
    suitableFor: 'Salaried and self-employed individuals',
    benefits: ['Additional tax benefit ₹50K', 'Government regulated', 'Low cost', 'Pension + Lumpsum'],
  },
  {
    slug: 'retirement-planning',
    title: 'Retirement Planning',
    shortDescription: 'Comprehensive retirement planning to ensure financial independence in your golden years.',
    icon: 'Sunset',
    riskLevel: 'Varies',
    suitableFor: 'Everyone aged 25+',
    benefits: ['Customized plan', 'Inflation adjusted', 'Multiple income streams', 'Peace of mind'],
  },
  {
    slug: 'education-planning',
    title: 'Children\'s Education Planning',
    shortDescription: 'Secure your child\'s future with a dedicated education fund for higher studies.',
    icon: 'GraduationCap',
    riskLevel: 'Moderate',
    suitableFor: 'Parents with children aged 0-15',
    benefits: ['Goal-based approach', 'Inflation adjusted', 'Flexible options', 'Early start advantage'],
  },
  {
    slug: 'goal-planning',
    title: 'Goal Based Planning',
    shortDescription: 'Create and track investment plans for life\'s important milestones and dreams.',
    icon: 'Goal',
    riskLevel: 'Varies',
    suitableFor: 'All investors with specific financial goals',
    benefits: ['Structured approach', 'Progress tracking', 'Risk-adjusted returns', 'Milestone celebrations'],
  },
  {
    slug: 'wealth-creation',
    title: 'Wealth Creation',
    shortDescription: 'Long-term wealth building strategies through diversified equity and hybrid investments.',
    icon: 'TrendingUp',
    riskLevel: 'Moderate to High',
    suitableFor: 'Long-term investors, wealth builders',
    benefits: ['Compounding power', 'Diversification', 'Professional guidance', 'Tax efficiency'],
  },
  {
    slug: 'portfolio-review',
    title: 'Portfolio Review',
    shortDescription: 'Regular assessment and rebalancing of your investment portfolio for optimal performance.',
    icon: 'ClipboardList',
    riskLevel: 'N/A',
    suitableFor: 'Existing investors',
    benefits: ['Performance analysis', 'Risk assessment', 'Rebalancing advice', 'Cost optimization'],
  },
  {
    slug: 'financial-planning',
    title: 'Financial Planning',
    shortDescription: 'Holistic financial planning covering investments, insurance, tax, and estate planning.',
    icon: 'FileText',
    riskLevel: 'N/A',
    suitableFor: 'Individuals and families',
    benefits: ['360° financial view', 'Tax optimization', 'Risk management', 'Legacy planning'],
  },
  {
    slug: 'term-insurance',
    title: 'Term Insurance',
    shortDescription: 'Protect your family\'s financial future with affordable high-coverage term life insurance.',
    icon: 'ShieldCheck',
    riskLevel: 'N/A',
    suitableFor: 'Breadwinners, young professionals',
    benefits: ['High coverage low premium', 'Family protection', 'Tax benefits', 'Critical illness riders'],
  },
  {
    slug: 'health-insurance',
    title: 'Health Insurance',
    shortDescription: 'Comprehensive health coverage for you and your family against medical emergencies.',
    icon: 'HeartPulse',
    riskLevel: 'N/A',
    suitableFor: 'Individuals and families',
    benefits: ['Cashless hospitalization', 'Pre/post hospitalization', 'No claim bonus', 'Tax benefits'],
  },
  {
    slug: 'loan-services',
    title: 'Loan Services',
    shortDescription: 'Get loans against your mutual fund investments without breaking your investment journey.',
    icon: 'HandCoins',
    riskLevel: 'N/A',
    suitableFor: 'Existing MF investors needing liquidity',
    benefits: ['Quick processing', 'Investments continue', 'Low interest rates', 'No prepayment penalty'],
  },
  {
    slug: 'emergency-fund',
    title: 'Emergency Fund Planning',
    shortDescription: 'Build a safety net of 6-12 months expenses through liquid and ultra-short term funds.',
    icon: 'Siren',
    riskLevel: 'Low',
    suitableFor: 'Everyone',
    benefits: ['Quick access', 'Better than savings account', 'Capital preservation', 'Liquidity'],
  },
  {
    slug: 'corporate-investments',
    title: 'Corporate Investments',
    shortDescription: 'Treasury management and surplus fund deployment solutions for businesses.',
    icon: 'Building',
    riskLevel: 'Low to Moderate',
    suitableFor: 'Companies, firms, trusts',
    benefits: ['Treasury optimization', 'Short-term parking', 'Better than FD returns', 'Professional management'],
  },
] as const;

export const WHY_CHOOSE_US = [
  { title: '15+ Years Experience', description: 'Over a decade of trusted financial guidance', icon: 'Award' },
  { title: 'AMFI Registered', description: 'Official AMFI Registration (ARN-144270)', icon: 'BadgeCheck' },
  { title: 'SEBI Compliant', description: 'Fully compliant with SEBI regulations', icon: 'Shield' },
  { title: '300+ Families Served', description: 'Growing community of satisfied investors', icon: 'Users' },
  { title: '₹10+ Cr Managed', description: 'Significant assets under management', icon: 'IndianRupee' },
  { title: 'Personal Financial Planning', description: 'Customized plans for every individual', icon: 'UserCheck' },
  { title: 'Transparent Advice', description: 'Honest, unbiased investment guidance', icon: 'Eye' },
  { title: 'Ethical Practices', description: 'Client interest always comes first', icon: 'Scale' },
  { title: 'Goal Based Investing', description: 'Investments aligned to your life goals', icon: 'Target' },
  { title: 'Long-term Wealth Creation', description: 'Building lasting financial prosperity', icon: 'TrendingUp' },
  { title: 'Dedicated Support', description: 'Personal relationship manager for you', icon: 'Headphones' },
  { title: 'Regular Portfolio Review', description: 'Periodic assessment and rebalancing', icon: 'RefreshCcw' },
] as const;

export const DISCLAIMER_TEXT = 'Mutual Fund investments are subject to market risks. Please read all scheme-related documents carefully before investing. Past performance is not indicative of future returns.';

export const BLOG_CATEGORIES = [
  { slug: 'mutual-funds', label: 'Mutual Funds' },
  { slug: 'insurance', label: 'Insurance' },
  { slug: 'tax-planning', label: 'Tax Planning' },
  { slug: 'market-updates', label: 'Market Updates' },
  { slug: 'retirement', label: 'Retirement' },
  { slug: 'financial-literacy', label: 'Financial Literacy' },
  { slug: 'investment-tips', label: 'Investment Tips' },
] as const;

export const GALLERY_TYPES = [
  { slug: 'all', label: 'All' },
  { slug: 'image', label: 'Photos' },
  { slug: 'video', label: 'Videos' },
  { slug: 'certificate', label: 'Certificates' },
  { slug: 'event', label: 'Events' },
  { slug: 'award', label: 'Awards' },
  { slug: 'poster', label: 'Posters' },
] as const;
